version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  publish:
    docker:
      - image: circleci/node:14.16.0
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Publish
          command: npm publish

workflows:
  test-and-publish:
    jobs:
      - node/test
      - publish:
          requires:
            - node/test
          filters:
            branch:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/